const EmployeeStatus = {
    REQUESTED: "REQUESTED",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    RESIGNED: "RESIGNED",
}

const Permissions: Record<string, string> = {
    /// GLOBAL
    ALL: "ALL",

    /// DASHBOARD
    READ_MANAGER_DASHBOARD: "READ_MANAGER_DASHBOARD",
    READ_SELF_DASHBOARD: "READ_SELF_DASHBOARD",

    /// -----
    /// EMPLOYEE
    READ_ALL_EMPLOYEE: "READ_ALL_EMPLOYEE",
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",

    /// ROLE
    READ_ALL_ROLE: "READ_ALL_ROLE",
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",

    /// DEPARTMENT
    READ_ALL_DEPARTMENT: "READ_ALL_DEPARTMENT",
    CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
    UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

    /// -----
    /// LEAVE
    READ_ALL_LEAVE: "READ_ALL_LEAVE",
    READ_SELF_LEAVE: "READ_SELF_LEAVE",
    CREATE_LEAVE: "CREATE_LEAVE",
    REQUEST_LEAVE: "REQUEST_LEAVE",
    UPDATE_LEAVE: "UPDATE_LEAVE",
    DELETE_LEAVE: "DELETE_LEAVE",
    READ_LEAVE_TYPE: "READ_LEAVE_TYPE",
    CREATE_LEAVE_TYPE: "CREATE_LEAVE_TYPE",
    UPDATE_LEAVE_TYPE: "UPDATE_LEAVE_TYPE",
    DELETE_LEAVE_TYPE: "DELETE_LEAVE_TYPE",


    /// -----
    /// ATTENDANCE
    READ_ALL_ATTENDANCE: "READ_ALL_ATTENDANCE",
    READ_SELF_ATTENDANCE: "READ_SELF_ATTENDANCE",
    READ_ATTENDANCE_SUMMARY: "READ_ATTENDANCE_SUMMARY",
    CREATE_ATTENDANCE: "CREATE_ATTENDANCE",
    CREATE_ALL_ATTENDANCE: "CREATE_ALL_ATTENDANCE",
    UPDATE_ATTENDANCE: "UPDATE_ATTENDANCE",
    DELETE_ATTENDANCE: "DELETE_ATTENDANCE",

    /// -----
    /// TODO: LATER : LEAD
}
export { EmployeeStatus, Permissions };