export const LeaveStatus = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED",
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
};
